services:
  web:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8888:3000
    env_file:
      - .env
    links:
      - "db:database"
    depends_on:
      - db

  db:
    image: postgres:16.1
    restart: always
    env_file:
      - .env
    ports:
      - ${VITE_DB_PORT}:5432
    expose:
      - ${VITE_DB_PORT}
    environment:
      POSTGRES_DB: ${VITE_DB_DATABASE}
      POSTGRES_USER: ${VITE_DB_USER}
      POSTGRES_PASSWORD: ${VITE_DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local